# Generated by Django 2.2 on 2020-07-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
