# Generated by Django 2.2 on 2020-07-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_auto_20200703_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='new_item'),
            preserve_default=False,
        ),
    ]
