# Generated by Django 2.2 on 2020-07-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0011_item_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
            ],
        ),
    ]
